version: "3"
services:
  postgres:
    image: postgres:latest
    ports:
    - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bike
  rso-bikes:
    image: jp8874/rso-teamlj-bikes:2.4
    ports:
    - 8082:8082
    environment:
      KUMULUZEE_DATASOURCES0_CONNECTIONURL: jdbc:postgresql://172.17.0.1:5434/bike
      KUMULUZEE_DATASOURCES0_USERNAME: postgres
      KUMULUZEE_DATASOURCES0_PASSWORD: postgres
      KUMULUZEE_DISCOVERY_ETCD_HOSTS: http://172.17.0.1:2379
    depends_on:
    - postgres

