kumuluzee:
  name: rso-bikes
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8082
    http:
      port: 8082
  datasources:
    - jndi-name: jdbc/BikeDS
      connection-url: jdbc:postgresql://35.228.47.159:5434/bike
      username: rso
      password: rso
      #connection-url: jdbc:postgresql://localhost:5434/bike
      #username: postgres
      #password: postgres
      max-pool-size: 20
  discovery:
    etcd:
      hosts: http://localhost:2379
  metrics:
    web-instrumentation:
    - name: bike-endpoint
      url-pattern: /v1/bikes/*
  health:
    checks:
      data-source-health-check:
        jndi-name: jdbc/BikeDS
