apiVersion: apps/v1
kind: Deployment
metadata:
  name: bikes-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bikes
  template:
    metadata:
      labels:
        app: bikes
    spec:
      containers:
      - name: bikes
        image: jp8874/rso-teamlj-bikes:2.9
        env:
          - name: KUMULUZEE_DISCOVERY_CLUSTER
            value: gcloud
          - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
            value: http://etcd:2379
        ports:
        - containerPort: 8082
          name: server
          protocol: TCP
